//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelcelVS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telcel
    {
        public int Id { get; set; }
        public string NombreUsuario { get; set; }
        public Nullable<int> IdTelefono { get; set; }
    
        public virtual Telefono Telefono { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
